excel:
  lastLink: https://www.loopnet.com/Listing/Interstate-4-State-Road-472-Orange-City-FL/21403891/
  lastRow: 101
home:
  citiesScanned: 0
  listingsScaned: 0
  listingsScanned: '4'
  recordsAdded: 0
